### ISSUE TITLE
Error when running vanilla_rnn_with_tfboard.py

### ISSUE THREAD

**Issue by quartermaine** [Hezi-Resheff/Oreilly-Learning-TensorFlow#22]
Getting the following error when I run vanilla_rnn_with_tfboard.py

```
Traceback (most recent call last):
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(128, 128), b.shape=(128, 128), m=128, n=128, k=128
	 [[Node: states/while/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](states/while/Switch_2:1, states/while/MatMul/Enter)]]
	 [[Node: linear_layer_weights_1/strided_slice/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_460_linear_layer_weights_1/strided_slice", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/tensorflow/vanilla_rnn_with_tfboard.py", line 127, in <module>
    summary, _ = sess.run([merged, train_step], feed_dict={_inputs: batch_x, y: batch_y})
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(128, 128), b.shape=(128, 128), m=128, n=128, k=128
	 [[Node: states/while/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](states/while/Switch_2:1, states/while/MatMul/Enter)]]
	 [[Node: linear_layer_weights_1/strided_slice/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_460_linear_layer_weights_1/strided_slice", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'states/while/MatMul', defined at:
  File "D:/tensorflow/vanilla_rnn_with_tfboard.py", line 67, in <module>
    all_hidden_states = tf.scan(rnn_step, processed_input, initializer=initial_hidden, name='states')
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 630, in scan
    maximum_iterations=n)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3194, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 619, in compute
    a_out = fn(packed_a, packed_elems)
  File "D:/tensorflow/vanilla_rnn_with_tfboard.py", line 54, in rnn_step
    tf.matmul(x, Wx) + b_rnn)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2122, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4278, in mat_mul
    name=name)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\quartermaine\Anaconda2\envs\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(128, 128), b.shape=(128, 128), m=128, n=128, k=128
	 [[Node: states/while/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](states/while/Switch_2:1, states/while/MatMul/Enter)]]
	 [[Node: linear_layer_weights_1/strided_slice/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_460_linear_layer_weights_1/strided_slice", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by quartermaine** [comment]
Closing issue
